/**
 * Template-based deliverable content generators.
 * Each function takes customer data and returns a markdown string
 * that serves as the auto-generated draft deliverable.
 */

const DOMAIN_LABELS: Record<string, string> = {
    scoreStrategy: 'AI Strategy & Vision',
    scoreData: 'Data Readiness & Governance',
    scoreTech: 'Technology & Infrastructure',
    scoreSecurity: 'Security & Compliance',
    scoreSkills: 'AI Skills & Talent',
    scoreOps: 'Organisational Readiness',
    scoreGovernance: 'AI Governance & Ethics',
    scoreFinancial: 'Financial & Operational Readiness',
}

function scoreLabel(score: number | null | undefined): string {
    if (!score) return 'Not Assessed'
    if (score < 2) return 'Initial'
    if (score < 3) return 'Developing'
    if (score < 4) return 'Defined'
    if (score < 4.5) return 'Managed'
    return 'Optimised'
}

function maturityBar(score: number | null | undefined): string {
    const val = score ?? 0
    const filled = Math.round(val)
    return '█'.repeat(filled) + '░'.repeat(5 - filled) + ` ${val.toFixed(1)}/5.0`
}

// ─── Phase 1 ─────────────────────────────────────────────────────────────────

function generateReadinessReport(customer: any, assessment: any | null): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

    const domainRows = Object.entries(DOMAIN_LABELS).map(([key, label]) => {
        const score = assessment?.[key] ?? null
        return `| ${label} | ${maturityBar(score)} | ${scoreLabel(score)} |`
    }).join('\n')

    const criticalDomains = Object.entries(DOMAIN_LABELS)
        .filter(([key]) => (assessment?.[key] ?? 0) < 2.5)
        .map(([, label]) => `- **${label}**: Score below 2.5 — immediate remediation recommended`)
        .join('\n') || '_No critical gaps identified._'

    const scores = Object.keys(DOMAIN_LABELS).map(k => assessment?.[k] ?? 0)
    const overall = scores.length > 0 ? (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(1) : 'N/A'

    return `# AI Readiness Assessment Report
**Client:** ${customer.name}
**Industry:** ${customer.industry || 'Not specified'}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Executive Summary

This report presents the findings of the AI Readiness Assessment conducted for **${customer.name}**. The assessment evaluated organisational maturity across eight critical domains using the UniSystems 5-Phase AI Consulting Framework.

**Overall Maturity Score: ${overall} / 5.0**

${Number(overall) >= 3.5
    ? `${customer.name} demonstrates a **solid foundation** for AI adoption. The organisation is positioned to progress into Use Case Identification and early Proof of Value activities.`
    : `${customer.name} is at an **early stage** of AI readiness. Foundational investments in data governance, skills, and strategy alignment are recommended before proceeding to full AI deployment.`
}

---

## Domain Maturity Assessment

| Domain | Maturity Score | Rating |
|--------|---------------|--------|
${domainRows}

---

## Critical Gaps Identified

${criticalDomains}

---

## Key Recommendations

1. **Establish an AI Steering Committee** — Formalise executive sponsorship and define AI governance responsibilities.
2. **Data Foundation First** — Prioritise data quality, cataloguing, and access control before scaling AI use cases.
3. **Skills Investment** — Launch an AI literacy programme and identify internal champions to accelerate adoption.
4. **Responsible AI Policy** — Define and communicate responsible AI principles before the first use case goes live.
5. **Phased Approach** — Begin with 1–2 high-impact, lower-risk use cases to build confidence and demonstrate value.

---

## Next Steps

Following this assessment, the recommended next phase is **Use Case Identification & Strategy Alignment**, where workshops will be conducted with business units to identify and prioritise AI opportunities aligned to the maturity findings above.

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

function generateAdoptionRoadmapV1(customer: any, assessment: any | null): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const phase = customer.currentPhase ?? 1

    return `# High-Level AI Adoption Roadmap
**Client:** ${customer.name}
**Industry:** ${customer.industry || 'Not specified'}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Overview

This roadmap outlines the recommended phased approach for ${customer.name}'s AI adoption journey, based on the findings from the Readiness Assessment.

---

## Engagement Phases & Timeline

| Phase | Title | Status | Est. Duration |
|-------|-------|--------|---------------|
| 1 | Discovery & Readiness Assessment | ${phase >= 1 ? '✅ Complete' : '⏳ Pending'} | 1–3 weeks |
| 2 | Use Case Identification & Strategy Alignment | ${phase >= 2 ? '✅ Complete' : '⏳ Pending'} | 1–2 weeks |
| 3 | Proof of Value Execution | ${phase >= 3 ? '✅ Complete' : '⏳ Pending'} | 3–6 weeks |
| 4 | Deployment & Change Management | ${phase >= 4 ? '✅ Complete' : '⏳ Pending'} | 4–8 weeks |
| 5 | Value Realization & Continuous Improvement | ${phase >= 5 ? '✅ Complete' : '⏳ Ongoing'} | Ongoing |

---

## Governance Structure

- **Executive Sponsor:** TBD
- **AI Programme Lead:** TBD
- **Steering Committee:** To be established in Phase 1
- **AI Champions Network:** To be identified in Phase 4

---

## Success Criteria

- Completion of the 8-domain maturity assessment
- Identification and prioritisation of at least 3 AI use cases
- At least 1 Proof of Value successfully executed
- Measurable ROI baseline established from Phase 2 analysis

---

## Risks & Mitigations

| Risk | Likelihood | Mitigation |
|------|-----------|------------|
| Lack of executive sponsorship | Medium | Secure sponsor commitment before Phase 2 kick-off |
| Data quality issues blocking AI adoption | High | Initiate data remediation workstream in parallel |
| Change resistance from employees | Medium | Early AI literacy programme and change management planning |
| Regulatory/compliance gaps | Low-Medium | Conduct AI regulatory gap analysis in Phase 1 |

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

// ─── Phase 2 ─────────────────────────────────────────────────────────────────

function generateUseCaseCatalogue(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

    const useCaseRows = useCases.length > 0
        ? useCases.map((uc, i) => `| ${i + 1} | ${uc.title} | ${uc.department || 'General'} | ${uc.priority || 'LOW'} | ${uc.status} | $${(uc.roiEstimate || 0).toLocaleString()} |`).join('\n')
        : '| — | No use cases identified yet | — | — | — | — |'

    const highPriority = useCases.filter(uc => uc.priority === 'HIGH')
    const totalROI = useCases.reduce((sum, uc) => sum + (uc.roiEstimate || 0), 0)

    return `# Prioritised Use Case Catalogue
**Client:** ${customer.name}
**Industry:** ${customer.industry || 'Not specified'}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Summary

| Metric | Value |
|--------|-------|
| Total Use Cases Identified | ${useCases.length} |
| High Priority Initiatives | ${highPriority.length} |
| Total Estimated Portfolio ROI | $${totalROI.toLocaleString()} |
| Departments Covered | ${[...new Set(useCases.map(uc => uc.department || 'General'))].join(', ') || 'N/A'} |

---

## Use Case Register

| # | Title | Department | Priority | Status | Est. ROI |
|---|-------|-----------|---------|--------|---------|
${useCaseRows}

---

## High-Priority Initiatives (Recommended Pilot Candidates)

${highPriority.length > 0
    ? highPriority.map(uc => `### ${uc.title}
- **Department:** ${uc.department || 'General'}
- **Description:** ${uc.description || 'No description provided.'}
- **Expected ROI:** $${(uc.roiEstimate || 0).toLocaleString()}
- **Current Status:** ${uc.status}
`).join('\n')
    : '_No high-priority use cases have been identified yet. Complete the use case discovery workshops to populate this section._'
}

---

## Recommended Pilot Sequence

Based on impact and feasibility scoring, the recommended sequence for piloting is:

${useCases
    .sort((a, b) => {
        const pOrder: Record<string, number> = { HIGH: 0, MEDIUM: 1, LOW: 2 }
        return (pOrder[a.priority ?? 'LOW'] ?? 2) - (pOrder[b.priority ?? 'LOW'] ?? 2)
    })
    .slice(0, 3)
    .map((uc, i) => `${i + 1}. **${uc.title}** (${uc.department || 'General'}) — ${uc.priority} priority`)
    .join('\n') || '_To be determined after workshop completion._'
}

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

function generateROIAnalysis(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const totalROI = useCases.reduce((sum, uc) => sum + (uc.roiEstimate || 0), 0)

    return `# Business Case & ROI Analysis
**Client:** ${customer.name}
**Industry:** ${customer.industry || 'Not specified'}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Executive Summary

This document presents the estimated business case and ROI projections for ${customer.name}'s AI adoption programme, based on the ${useCases.length} use cases identified during the Strategy Alignment phase.

**Total Estimated Annual Portfolio Value: $${totalROI.toLocaleString()}**

---

## ROI by Initiative

| Initiative | Department | Priority | Est. Annual Value | 3-Year Value |
|-----------|-----------|---------|-----------------|-------------|
${useCases.map(uc => `| ${uc.title} | ${uc.department || 'General'} | ${uc.priority || 'LOW'} | $${(uc.roiEstimate || 0).toLocaleString()} | $${((uc.roiEstimate || 0) * 3).toLocaleString()} |`).join('\n') || '| No use cases defined | — | — | — | — |'}

**Totals** | | | **$${totalROI.toLocaleString()}** | **$${(totalROI * 3).toLocaleString()}** |

---

## Investment Categories

- **Consulting & Implementation:** To be defined in PoV planning
- **Licensing & Infrastructure:** To be defined based on technology stack
- **Training & Change Management:** Estimated 15–20% of total project cost
- **Ongoing Operations:** Estimated 20% of Year 1 cost annually

---

## Key Assumptions

1. ROI estimates are based on productivity and efficiency gains, not headcount reduction
2. Figures represent annualised steady-state value, typically realised 6–12 months post-deployment
3. All estimates should be validated with business unit owners during Phase 3 PoV measurement
4. Conservative factor of 0.7 applied — actual outcomes may exceed projections

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

function generateAdoptionRoadmapV2(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const pilots = useCases.filter(uc => uc.priority === 'HIGH').slice(0, 3)

    return `# Updated AI Adoption Roadmap
**Client:** ${customer.name}
**Date:** ${date}
**Version:** 2.0 (Post Use Case Strategy Alignment)
**Prepared by:** UniSystems AI Consulting Practice

---

## Phase 3 Pilot Selection

Based on use case prioritisation workshops, the following initiatives are recommended for the Proof of Value phase:

${pilots.length > 0
    ? pilots.map((uc, i) => `**Pilot ${i + 1}: ${uc.title}**
- Department: ${uc.department || 'General'}
- Expected Value: $${(uc.roiEstimate || 0).toLocaleString()}
- Success Metric: TBD with business unit owner
`).join('\n')
    : '_Pilot candidates to be confirmed after use case prioritisation._'
}

---

## Updated Timeline

| Phase | Activities | Timeline |
|-------|-----------|----------|
| Phase 3: PoV | Pilot setup, execution, measurement | Weeks 1–8 |
| Phase 4: Deployment | Phased rollout, training, monitoring | Weeks 9–20 |
| Phase 5: Value | KPI measurement, continuous improvement | Week 21+ |

---

## Deployment Strategy

- **Approach:** Phased rollout by department, starting with PoV cohort
- **Change Management:** AI Champions to be identified in each business unit
- **Training Model:** Role-based workshops + self-service learning materials
- **Governance:** Steering committee reviews monthly during rollout

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

// ─── Phase 3 ─────────────────────────────────────────────────────────────────

function generatePovResultsReport(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const pilots = useCases.filter(uc => uc.status === 'PILOTING' || uc.status === 'APPROVED')

    return `# PoV Results & Recommendations Report
**Client:** ${customer.name}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## PoV Summary

| Metric | Value |
|--------|-------|
| Pilots Executed | ${pilots.length} |
| Departments Involved | ${[...new Set(pilots.map(p => p.department || 'General'))].join(', ') || 'TBD'} |
| PoV Duration | TBD |
| Overall Outcome | Go / No-Go (confirm after review) |

---

## Pilot Results

${pilots.length > 0
    ? pilots.map(p => `### ${p.title}
- **Status:** ${p.status}
- **Department:** ${p.department || 'General'}
- **Target ROI:** $${(p.roiEstimate || 0).toLocaleString()}
- **Usage Analytics:** _To be populated post-PoV_
- **User Feedback Summary:** _To be populated post-PoV_
- **KPIs Achieved:** _To be populated post-PoV_
`).join('\n')
    : '_No pilots have been initiated yet. This section will be populated once PoV execution begins._'
}

---

## Key Learnings

_To be completed after PoV execution. Capture:_
- _What worked well_
- _Technical challenges encountered_
- _User adoption observations_
- _Recommended adjustments for full rollout_

---

## Recommendation

☐ **Go** — Proceed to full deployment with the following adjustments: [TBD]
☐ **Conditional Go** — Proceed once the following conditions are met: [TBD]
☐ **No-Go** — Rationale: [TBD]

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please complete with actual PoV data before sharing with the client._`
}

function generateSolutionGovernancePlan(customer: any): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    return `# Refined Solution Design & Governance Plan
**Client:** ${customer.name}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Solution Architecture

_To be completed based on PoV findings. Document:_
- Technical architecture diagram
- Integration points with existing systems
- Data flows and privacy considerations
- AI model selection and configuration

---

## Governance Framework

| Area | Owner | Cadence | Notes |
|------|-------|---------|-------|
| AI Steering Committee | Executive Sponsor | Monthly | Strategic oversight |
| Usage Monitoring | IT/Security Team | Weekly | Compliance and policy adherence |
| Model Performance Review | AI Lead | Quarterly | Accuracy and bias monitoring |
| User Feedback Collection | Change Management | Ongoing | Continuous improvement |

---

## Responsible AI Controls

- [ ] Bias detection process defined
- [ ] Explainability requirements documented
- [ ] Data privacy review completed
- [ ] Acceptable use policy published to all users
- [ ] Escalation path for AI-related issues established

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

function generateGoNoGoRolloutPlan(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    return `# Go/No-Go Decision & Rollout Plan
**Client:** ${customer.name}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Go/No-Go Decision Summary

| Criterion | Status | Notes |
|-----------|--------|-------|
| PoV success criteria met | ⬜ TBD | Validate after PoV measurement |
| Security & compliance sign-off | ⬜ TBD | Required before rollout |
| Executive sponsor approval | ⬜ TBD | Formal sign-off required |
| Training materials prepared | ⬜ TBD | Phase 4 prerequisite |
| Support model defined | ⬜ TBD | Hypercare period planned |

**Decision:** ☐ GO  ☐ CONDITIONAL GO  ☐ NO-GO

---

## Rollout Plan (if Go)

| Wave | Departments | Users | Timeline |
|------|------------|-------|----------|
| Wave 1 (Pilot Cohort) | ${useCases.filter(u => u.status === 'PILOTING').map(u => u.department || 'TBD').join(', ') || 'TBD'} | ~TBD | Week 1–2 |
| Wave 2 (Early Majority) | TBD | ~TBD | Week 3–6 |
| Wave 3 (Full Deployment) | All departments | All users | Week 7–10 |

---

## Updated Success Metrics for Full Rollout

_Refine based on PoV learnings:_
- Weekly active AI users: Target TBD
- Productivity gain per user: Target TBD
- Time saved per task type: Target TBD
- User satisfaction score (NPS): Target TBD

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and customise before sharing with the client._`
}

// ─── Phase 4 ─────────────────────────────────────────────────────────────────

function generateRolloutChecklist(customer: any): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    return `# Enterprise Rollout Completion Checklist
**Client:** ${customer.name}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Pre-Rollout Readiness

- [ ] All user licences assigned and verified
- [ ] AI features enabled in tenant/environment configuration
- [ ] Data labelling and sensitivity policies applied
- [ ] Security and compliance review signed off
- [ ] Training materials finalised and distributed
- [ ] AI Champions identified and briefed in each department
- [ ] Feedback and support channels established
- [ ] Hypercare support model activated

---

## Rollout Execution

- [ ] Wave 1 deployment completed (early adopters)
- [ ] Wave 2 deployment completed (broader rollout)
- [ ] Wave 3 deployment completed (full organisation)
- [ ] All role-based training workshops delivered
- [ ] User community platform launched
- [ ] Communication announcements sent to all users

---

## Post-Rollout Validation

- [ ] Adoption metrics dashboard live
- [ ] First weekly usage report generated
- [ ] Governance committee post-rollout review meeting held
- [ ] User satisfaction survey distributed (Week 2 post-launch)
- [ ] Hypercare period concluded and steady-state support activated
- [ ] Handover to ongoing operations team completed

---

## Sign-Off

| Role | Name | Signature | Date |
|------|------|-----------|------|
| Executive Sponsor | | | |
| Project Lead (UniSystems) | | | |
| IT/Security Lead | | | |
| Change Management Lead | | | |

---
_This document was auto-generated by the UniSystems AI Consulting Platform._`
}

function generateAdoptionStatusReport(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const production = useCases.filter(uc => uc.status === 'PRODUCTION')
    return `# Adoption Status Report
**Client:** ${customer.name}
**Report Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Deployment Summary

| Metric | Value |
|--------|-------|
| Use Cases in Production | ${production.length} |
| Total Departments Reached | ${[...new Set(production.map(p => p.department || 'General'))].join(', ') || 'TBD'} |
| Deployment Waves Completed | TBD |
| Active Users (Week 1) | TBD |

---

## Adoption Highlights

_To be populated post-rollout. Include:_
- Key adoption stories and early wins
- Departments showing highest engagement
- Most popular use cases by usage volume
- User testimonials and feedback themes

---

## Adoption Metrics

| KPI | Target | Actual | Status |
|-----|--------|--------|--------|
| Weekly Active Users | TBD | TBD | ⬜ |
| Training Completion Rate | >80% | TBD | ⬜ |
| User Satisfaction Score | >7/10 | TBD | ⬜ |
| Use Cases in Active Use | ${production.length} | TBD | ⬜ |

---

## Challenges & Mitigations

_Document any adoption blockers encountered and how they were addressed._

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please complete with actual rollout data before sharing with the client._`
}

// ─── Phase 5 ─────────────────────────────────────────────────────────────────

function generateValueRealizationReport(customer: any, useCases: any[], assessment: any | null): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const production = useCases.filter(uc => uc.status === 'PRODUCTION')
    const projectedROI = useCases.reduce((sum, uc) => sum + (uc.roiEstimate || 0), 0)
    const scores = Object.keys(DOMAIN_LABELS).map(k => assessment?.[k] ?? 0)
    const avgMaturity = scores.length > 0 ? (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(1) : 'N/A'

    return `# Value Realization Report
**Client:** ${customer.name}
**Industry:** ${customer.industry || 'Not specified'}
**Report Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Executive Summary

This report compares the actual benefits achieved by ${customer.name} against the projected business case established in Phase 2, and provides a roadmap for continued value expansion.

---

## Value vs. Business Case

| Metric | Projected (Phase 2) | Actual | Variance |
|--------|---------------------|--------|---------|
| Total Annual ROI | $${projectedROI.toLocaleString()} | TBD | TBD |
| Use Cases in Production | ${useCases.length} | ${production.length} | ${production.length - useCases.length} |
| AI Maturity Score | Baseline: ${avgMaturity} | TBD | TBD |

---

## Value Realized by Initiative

${production.length > 0
    ? production.map(uc => `### ${uc.title}
- **Projected Annual Value:** $${(uc.roiEstimate || 0).toLocaleString()}
- **Actual Value Achieved:** TBD
- **Key Benefits Realized:** _To be populated from analytics_
`).join('\n')
    : '_No use cases in production yet. This section will populate as use cases reach the PRODUCTION status._'
}

---

## Maturity Journey

| Phase Completed | Key Achievement |
|----------------|-----------------|
| Phase 1: Discovery | Baseline maturity score of ${avgMaturity}/5.0 established |
| Phase 2: Strategy | ${useCases.length} use cases identified and prioritised |
| Phase 3: PoV | Initial pilots validated business value |
| Phase 4: Deployment | ${production.length} use cases deployed to production |
| Phase 5: Value | Ongoing KPI measurement and optimisation |

---

## Recommendations for Next Phase

1. **Expand successful use cases** to additional departments not yet covered
2. **Identify second-wave opportunities** based on lessons learned
3. **Invest in advanced capabilities** — consider Agentic AI for high-complexity processes
4. **Continue maturity improvement** — target 4.0+ across all 8 domains

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Please review and validate with actual measured data._`
}

function generateImprovementBacklog(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    return `# Continuous Improvement Backlog
**Client:** ${customer.name}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Backlog Overview

This backlog captures enhancement ideas, optimization opportunities, and next-phase initiatives, prioritised by impact.

---

## Active Improvement Items

| ID | Enhancement | Impact | Effort | Priority | Status |
|----|------------|--------|--------|---------|--------|
| 001 | Expand AI rollout to remaining departments | High | Medium | High | ⬜ Backlog |
| 002 | Refine prompting strategies based on usage analytics | Medium | Low | Medium | ⬜ Backlog |
| 003 | Establish AI model performance review cadence | High | Low | High | ⬜ Backlog |
| 004 | Develop advanced use cases (Phase 2 pipeline) | High | High | Medium | ⬜ Backlog |
| 005 | Create enterprise Agentic AI experiences | Very High | Very High | Low | ⬜ Future |

---

## Use Case Expansion Candidates

${useCases.filter(uc => uc.status !== 'PRODUCTION').map(uc =>
    `- **${uc.title}** (${uc.department || 'General'}) — ${uc.priority} priority, currently ${uc.status}`
).join('\n') || '_All identified use cases are in production. Conduct another discovery workshop to identify new opportunities._'}

---

## Review Cadence

| Review Type | Frequency | Participants |
|-------------|----------|-------------|
| Operational Review | Monthly | AI Champions, IT Lead |
| Strategic Review | Quarterly | Executive Sponsor, Programme Lead |
| Value Assessment | Bi-annually | Finance, Business Unit Heads |

---
_This document was auto-generated by the UniSystems AI Consulting Platform._`
}

function generateEnterpriseAgentsPlan(customer: any, useCases: any[]): string {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    return `# Enterprise AI Agents Plan
**Client:** ${customer.name}
**Date:** ${date}
**Prepared by:** UniSystems AI Consulting Practice

---

## Vision

Following successful foundational AI adoption, ${customer.name} is positioned to move beyond standard AI assistants into custom **Agentic AI** solutions — autonomous agents that integrate with business processes to deliver compounding value.

---

## Recommended Agent Opportunities

| Agent | Business Process | Est. Value | Complexity | Priority |
|-------|-----------------|-----------|-----------|---------|
| Procurement Intelligence Agent | Supplier analysis, contract review | High | Medium | High |
| Customer Insight Agent | CRM data analysis, churn prediction | Very High | High | Medium |
| Operations Optimisation Agent | Process monitoring, anomaly detection | High | Medium | High |
| Knowledge Management Agent | Internal Q&A, document retrieval | Medium | Low | High |

---

## Proposed Agent Architecture

_To be customised based on ${customer.name}'s technology stack:_

- **Orchestration Layer:** Agent framework (e.g., Azure AI Foundry, LangGraph, AutoGen)
- **Data Sources:** CRM, ERP, document stores, real-time operational data
- **Integration Points:** Existing business applications via APIs
- **Governance Controls:** Human-in-the-loop for high-stakes decisions, full audit trails

---

## Implementation Roadmap

| Quarter | Milestone |
|---------|-----------|
| Q1 | Agent opportunity assessment and architecture design |
| Q2 | First agent Proof of Value (Knowledge Management) |
| Q3 | Second agent deployment (Operations Optimisation) |
| Q4 | Enterprise-scale multi-agent orchestration |

---
_This document was auto-generated by the UniSystems AI Consulting Platform. Review with the technical team before sharing with the client._`
}

// ─── Dispatcher ───────────────────────────────────────────────────────────────

export function generateDeliverableContent(
    deliverableKey: string,
    customer: any,
    data: { assessment?: any; useCases?: any[] }
): string {
    const assessment = data.assessment ?? null
    const useCases = data.useCases ?? []

    switch (deliverableKey) {
        // Phase 1
        case 'readiness_report':        return generateReadinessReport(customer, assessment)
        case 'adoption_roadmap_v1':     return generateAdoptionRoadmapV1(customer, assessment)
        // Phase 2
        case 'usecase_catalogue':       return generateUseCaseCatalogue(customer, useCases)
        case 'roi_analysis':            return generateROIAnalysis(customer, useCases)
        case 'adoption_roadmap_v2':     return generateAdoptionRoadmapV2(customer, useCases)
        // Phase 3
        case 'pov_results_report':      return generatePovResultsReport(customer, useCases)
        case 'solution_governance_plan': return generateSolutionGovernancePlan(customer)
        case 'gono_rollout_plan':       return generateGoNoGoRolloutPlan(customer, useCases)
        // Phase 4
        case 'rollout_checklist':       return generateRolloutChecklist(customer)
        case 'training_materials_repo': return `# Adoption & Training Materials Repository\n\n_Use this section to list and link to all training materials, decks, and user guides created for ${customer.name}. Upload files using the document attachment feature below._`
        case 'adoption_status_report':  return generateAdoptionStatusReport(customer, useCases)
        // Phase 5
        case 'value_realization_report': return generateValueRealizationReport(customer, useCases, assessment)
        case 'improvement_backlog':     return generateImprovementBacklog(customer, useCases)
        case 'enterprise_agents_plan':  return generateEnterpriseAgentsPlan(customer, useCases)

        default:
            return `# ${deliverableKey}\n\n_Auto-generation is not configured for this deliverable. Please author this document manually and upload the final version._`
    }
}
